name: Types, Tests and Linting

on:
  push:
  # While `push` tests that that the exact branch works,
  # `pull_request` tests that the branch works even after a merge to main
  pull_request:
    branches: [ main ]

jobs:
  testbuild:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
      - run: npm test
